# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E9DBFF
background         #16141A
cursor             #86799D

active_tab_foreground     #16141A
active_tab_background     #E9DBFF
inactive_tab_foreground   #E9DBFF
inactive_tab_background   #16141A

active_border_color   #E9DBFF
inactive_border_color #16141A
bell_border_color     #120B23

color0      #3E3B42
color1		#120B23
color2		#1A122D
color3		#31227B
color4		#493967
color5		#705998
color6		#9073BE
color7		#D7C4F6
color8		#9689AC
color9		#180F2F
color10		#22183C
color11		#412EA4
color12		#614B8A
color13		#9677CA
color14		#C099FE
color15		#D7C4F6
