# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(16141A)
$foreground = rgb(E9DBFF)
$color0 = rgb(3E3B42)
$color1 = rgb(120B23)
$color2 = rgb(1A122D)
$color3 = rgb(31227B)
$color4 = rgb(493967)
$color5 = rgb(705998)
$color6 = rgb(9073BE)
$color7 = rgb(D7C4F6)
$color8 = rgb(9689AC)
$color9 = rgb(180F2F)
$color10 = rgb(22183C)
$color11 = rgb(412EA4)
$color12 = rgb(614B8A)
$color13 = rgb(9677CA)
$color14 = rgb(C099FE)
$color15 = rgb(D7C4F6)
